strict: true
relative_results: true
disable_update_check: true
retain_public: true
retain_objc_accessible: true
retain_codable_properties: true
retain_equatable_properties: true
report_include:
  - Sources/**/*.swift
