#!/usr/bin/env python3
"""Render the package catalog from locked public flake metadata, without builds."""

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "docs/catalog.md"


def text(value: str) -> str:
    """Keep upstream descriptions on one Markdown line without HTML markup."""
    return " ".join(value.split()).replace("<", "&lt;").replace(">", "&gt;")


def render(inventory: dict, policy: dict, root: Path = ROOT) -> str:
    systems = sorted(inventory)
    names = sorted({name for packages in inventory.values() for name in packages})
    lines = [
        "# Package catalog",
        "",
        "<!-- Generated by scripts/package-catalog.py; edit package metadata, then regenerate. -->",
        "",
        f"Browse all {len(names)} public packages below. Platform lists come from the",
        "locked flake's exported packages. They describe availability, not a promise",
        "that every package has passed a native build or runtime test.",
        "",
        "Each command builds a package on your current platform. It does not install",
        "or launch it. Use a flake input and commit your lock file for reproducible",
        "configuration, as shown in the [usage guide](../README.md#use).",
        "",
        "Direct flake outputs allow unfree packages internally. Review the linked",
        "upstream terms before using them. The [licensing policy](package-licensing.md)",
        "explains selective consent, hosted builds, and redistribution limits.",
        "A license label is metadata, not an additional permission grant.",
        "",
        "## Find a package",
        "",
    ]
    lines.extend(f"- [{name}](#{name})" for name in names)
    lines += ["", "## Packages", ""]
    for name in names:
        variants = {
            system: inventory[system][name]
            for system in systems
            if name in inventory[system]
        }
        metadata = next(iter(variants.values()))
        source = Path("pkgs/by-name") / name[:2] / name
        if not (root / source / "package.nix").is_file():
            raise ValueError(f"missing package source: {name}")
        lines += [f"### {name}", "", text(metadata["description"]) + ".", ""]
        links = [f"[Recipe](../{source}/package.nix)"]
        if (root / source / "README.md").is_file():
            links.append(f"[Package guide](../{source}/README.md)")
        if metadata["homepage"]:
            links.append(f"[Upstream]({metadata['homepage']})")
        lines += [" · ".join(links), ""]
        for system, variant in variants.items():
            licenses = ", ".join(
                f"[{license['name']}]({license['url']})"
                if license["url"]
                else license["name"]
                for license in variant["licenses"]
            )
            restricted = (
                "; includes unfree terms"
                if any(not item["free"] for item in variant["licenses"])
                else ""
            )
            lines.append(
                f"- `{system}`: {text(variant['version'])}; {licenses}{restricted}."
            )
        if name in policy:
            lines += ["", "Hosted CI: " + text(policy[name])]
        lines += [
            "",
            "```sh",
            f"nix build github:nix-forge/nixpkgs-personal#{name}",
            "```",
            "",
        ]
    lines += [
        "## Maintain this catalog",
        "",
        "Run from a checkout with Nix and Python 3:",
        "",
        "```sh",
        "python3 scripts/package-catalog.py",
        "python3 scripts/package-catalog.py --check",
        "```",
        "",
        "The generator evaluates the locked public package outputs with import from",
        "derivation disabled. It reads descriptions, versions, platforms and license",
        "links from package metadata, and hosted exclusions from `.github/ci-policy.json`.",
        "It neither builds vendor payloads nor refreshes the lock file.",
        "Regenerate after changing package metadata, inventory, or Nixpkgs pins.",
        "Stage new package files first so Nix includes them in its Git source.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if the checked-in catalog differs"
    )
    args = parser.parse_args()
    result = subprocess.run(
        [
            "nix",
            "eval",
            "--json",
            "--no-update-lock-file",
            "--option",
            "allow-import-from-derivation",
            "false",
            ".#packages",
            "--apply",
            (ROOT / "scripts/package-catalog.nix").read_text(),
        ],
        cwd=ROOT,
        check=True,
        stdout=subprocess.PIPE,
        text=True,
    )
    inventory = json.loads(result.stdout)
    policy = json.loads((ROOT / ".github/ci-policy.json").read_text())
    rendered = render(inventory, policy)
    if args.check:
        if not CATALOG.exists() or CATALOG.read_text() != rendered:
            print(
                "Package catalog is stale; run python3 scripts/package-catalog.py",
                file=sys.stderr,
            )
            return 1
        print("Package catalog matches locked metadata.")
    else:
        CATALOG.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
