name: Dependency review
on:
  pull_request:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
    inputs:
      base_ref:
        description: Base commit or ref to compare.
        required: true
        type: string
      head_ref:
        description: Head commit or ref to compare.
        required: true
        type: string
permissions: {}
jobs:
  dependency-review:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          base-ref: ${{ inputs.base_ref }}
          head-ref: ${{ inputs.head_ref }}
