name: NUR compatibility
on:
  schedule:
    - cron: 41 6 * * 1
  workflow_dispatch:
permissions: {}
jobs:
  nur:
    name: NUR compatibility
    permissions:
      contents: read
    uses: nix-forge/ci/.github/workflows/nur.yml@8df2d2979c33ca75ddbd3a878c834ca96b01dc38 # v2.5.2
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
