name: NUR compatibility
on:
  schedule:
    - cron: 41 6 * * 1
  workflow_dispatch:
permissions: {}
jobs:
  nur:
    name: NUR compatibility
    permissions:
      contents: read
    uses: nix-forge/ci/.github/workflows/nur.yml@13ad6e366ec01e317705d750fc512d33ecc15f6c # v2.8.0
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
